
export const getMethodsList = () => Array.from([
  'Foxbit WebSocket API',
  ...Object.keys(paramsList),
])

export const paramsList = ({
  // 'AuthenticateUser': ['APIKey', 'Nonce', 'UserId', 'Signature'],
  // 'Authenticate2FA': ['Code'],
  'SendOrder': ['OMSId', 'InstrumentId', 'AccountId', 'TimeInForce', 'ClientOrderId', 'OrderIdOCO', 'UseDisplayQuantity', 'Side', 'Quantity', 'OrderType', 'PegPriceType', 'LimitPrice'],
  'CancelOrder': ['OMSId', 'AccountId', 'ClOrderId', 'OrderId'],
  'GetOrderFee': ['OMSId', 'AccountId', 'InstrumentId', 'ProductId', 'Amount', 'OrderType', 'MakerTaker', 'Side', 'Quantity'],
  'GetOrderHistory': ['OMSId', 'AccountId', 'Depth'],
  'GetOrderStatus': ['AccountId', 'OrderId'],
  'GetOpenOrders': ['OMSId', 'AccountId'],
  'CancelAllOrders': ['IntrumentId'],
  'GetWithdrawTickets': ['Limit'],
  'GetDepositTickets': [],
  'GetAccountInfo': ['OMSId', 'AccountId'],
  'GetAccountPositions': ['OMSId', 'AccountId'],
  'GetInstrument': ['InstrumentId'],
  'GetInstruments': ['OMSId'],
  'GetProducts': ['OMSId'],
  'GetL2Snapshot': ['OMSId', 'InstrumentId', 'Depth'],
  'GetTickerHistory': ['InstrumentId', 'Interval', 'FromDate', 'ToDate'],
  // 'GetTradesHistory': ['omsId', 'accountId', 'instrumentId', 'tradeId', 'orderId', 'userId', 'startTimeStamp', 'endTimeStamp', 'depth', 'startIndex', 'executionId'],
  'GetUserInfo': ['additionalProperties'],
  'GetUserPermissions': [],
  'Logout': [],
  'SubscribeLevel1': ['InstrumentId', 'MarketId'],
  'UnsubscribeLevel1': ['OMSId', 'InstrumentId'],
  // 'SubscribeLevel1Markets': [],
  'SubscribeLevel2': ['OMSId', 'InstrumentId'],
  'UnsubscribeLevel2': ['OMSId', 'InstrumentId'],
  'SubscribeTicker': ['OMSId', 'InstrumentId', 'Interval', 'IncludeLastCount'],
  'UnsubscribeTicker': ['InstrumentId'],
  'GetAccountTrades': ['OMSId', 'AccountId', 'StartIndex', 'Count'],
  'SubscribeTrades': ['OMSId', 'InstrumentId', 'IncludeLastCount',],
  'UnsubscribeTrades': ['OMSId', 'InstrumentId'],
  'SubscribeAccountEvents': [],
})
