import { RequestModel } from '../../../assets/js/models/request.model.js'

export const getEndpointsList = () => Array.from([
  new RequestModel('Binance Rest API'),
  new RequestModel('Test Connectivity', 'GET', '/api/v3/ping'),
  new RequestModel('Check Server Time', 'GET', '/api/v3/time'),
  new RequestModel('Exchange Information', 'GET', '/api/v3/exchangeInfo'),
  new RequestModel('Order Book', 'GET', '/api/v3/depth'),
  new RequestModel('Recent Trades List', 'GET', '/api/v3/trades'),
  new RequestModel('Compressed/Aggregate Trades List', 'GET', '/api/v3/aggTrades'),
  new RequestModel('Old Trade Lookup', 'GET', '/api/v3/historicalTrades'),
  new RequestModel('Kline/Candlestick Data', 'GET', '/api/v3/klines'),
  new RequestModel('UIKlines', 'GET', '/api/v3/uiKlines'),
  new RequestModel('Current Average Price', 'GET', '/api/v3/avgPrice'),
  new RequestModel('Rolling window price change statistics', 'GET', '/api/v3/ticker'),
  new RequestModel('24hr Ticker Price Change Statistics', 'GET', '/api/v3/ticker/24hr'),
  new RequestModel('Trading Day Ticker', 'GET', '/api/v3/ticker/tradingDay'),
  new RequestModel('Symbol Price Ticker', 'GET', '/api/v3/ticker/price'),
  new RequestModel('Symbol Order Book Ticker', 'GET', '/api/v3/ticker/bookTicker'),
  new RequestModel('Account Trade List (USER_DATA)', 'GET', '/api/v3/myTrades'),
  new RequestModel('Query Open OCO (USER_DATA)', 'GET', '/api/v3/openOrderList'),
  new RequestModel('Query all OCO (USER_DATA)', 'GET', '/api/v3/allOrderList'),
  new RequestModel('Query Order (USER_DATA)', 'GET', '/api/v3/order'),
  new RequestModel('Query OCO (USER_DATA)', 'GET', '/api/v3/orderList'),
  new RequestModel('Query Commission Rates (USER_DATA)', 'GET', '/api/v3/account/commission'),
  new RequestModel('Account Information (USER_DATA)', 'GET', '/api/v3/account'),
  new RequestModel('Current Open Orders (USER_DATA)', 'GET', '/api/v3/openOrders'),
  new RequestModel('All Orders (USER_DATA)', 'GET', '/api/v3/allOrders'),
  new RequestModel('Query Allocations (USER_DATA)', 'GET', '/api/v3/myAllocations'),
  new RequestModel('Query Prevented Matches (USER_DATA)', 'GET', '/api/v3/myPreventedMatches'),
  new RequestModel('Account Information (USER_DATA)', 'GET', '/api/v3/account'),
  new RequestModel('Query Current Order Count Usage (TRADE)', 'GET', '/api/v3/rateLimit/order'),
  new RequestModel('Test New Order (TRADE)', 'POST', '/api/v3/order/test'),
  new RequestModel('Test new order using SOR (TRADE)', 'POST', '/api/v3/sor/order/test'),
  new RequestModel('New order using SOR (TRADE)', 'POST', '/api/v3/sor/order'),
  new RequestModel('Cancel and Replace an Order (TRADE)', 'POST', '/api/v3/order/cancelReplace'),
  new RequestModel('New Order (TRADE)', 'POST', '/api/v3/order'),
  new RequestModel('New OCO (TRADE)', 'POST', '/api/v3/order/oco'),
  new RequestModel('Cancel Order (TRADE)', 'DELETE', '/api/v3/order'),
  new RequestModel('Cancel OCO (TRADE)', 'DELETE', '/api/v3/orderList'),
  new RequestModel('Cancel all Open Orders on a Symbol (TRADE)', 'DELETE', '/api/v3/openOrders'),
  new RequestModel('Create a ListenKey (USER_STREAM)', 'POST', '/api/v3/userDataStream'),
  new RequestModel('Ping/Keep-alive a ListenKey (USER_STREAM)', 'PUT', '/api/v3/userDataStream'),
  new RequestModel('Close a ListenKey (USER_STREAM)', 'DELETE', '/api/v3/userDataStream'),
])
