
export const getDefaultInputsList = () => ({
  'foxbit': [],
  'binance': ['timestamp', 'api_key', 'signature'],
})

export const getEndpointsList = () => ({
  'foxbit': [],
  'binance': [
    '---',
    'ping',
    'time',
    'exchangeInfo',
    'depth',
    'trades.recent',
    'trades.historical',
    'trades.aggregate',
    'klines',
    'uiKlines',
    'avgPrice',
    'ticker',
    'ticker.24hr',
    'ticker.tradingDay',
    'ticker.price',
    'ticker.book',
    'session.status',
    'session.logon',
    'session.logout',
    'order.status',
    'order.place',
    'order.test',
    'order.cancel',
    'order.cancelReplace',
    'openOrders.status',
    'openOrders.cancelAll',
    'orderList.status',
    'orderList.place',
    'orderList.cancel',
    'openOrderLists.status',
    'sor.order.place',
    'sor.order.test',
    'account.status',
    'account.rateLimits.orders',
    'account.commission',
    'allOrders',
    'allOrderLists',
    'myTrades',
    'myPreventedMatches',
    'myAllocations',
  ],
})

export const getEndpointInputsList = () => ({
  'foxbit': { '': [] },
  'binance': {
    'ping': [],
    'time': [],
    'exchangeInfo': ['symbol'],
    'depth': ['symbol', 'limit'],
    'trades.recent': ['symbol', 'limit'],
    'trades.historical': ['symbol', 'fromId', 'limit'],
    'trades.aggregate': ['symbol', 'fromId', 'limit'],
    'klines': ['symbol', 'interval', 'startTime', 'limit'],
    'uiKlines': ['symbol', 'interval', 'startTime', 'limit'],
    'avgPrice': ['symbol'],
    'ticker': ['symbol'],
    'ticker.24hr': ['symbol'],
    'ticker.tradingDay': ['symbol'],
    'ticker.price': ['symbol'],
    'ticker.book': ['symbol'],
    'session.status': ['apiKey', 'signature', 'timestamp'],
    'session.logon': [],
    'session.logout': [],
    'order.status': ['symbol', 'orderId', 'apiKey', 'signature', 'timestamp'],
    'order.place': ['symbol', 'side', 'type', 'timeInForce', 'price', 'quantity', 'apiKey', 'signature', 'timestamp'],
    'order.test': ['symbol', 'side', 'type', 'timeInForce', 'price', 'quantity', 'apiKey', 'signature', 'timestamp'],
    'order.cancel': ['symbol', 'origClientOrderId', 'apiKey', 'signature', 'timestamp'],
    'order.cancelReplace': ['symbol', 'cancelReplaceMode', 'cancelOrigClientOrderId', 'side', 'type', 'timeInForce', 'price', 'quantity', 'apiKey', 'signature', 'timestamp'],
    'openOrders.status': ['symbol', 'apiKey', 'signature', 'timestamp'],
    'openOrders.cancelAll': ['symbol', 'apiKey', 'signature', 'timestamp'],
    'orderList.status': ['origClientOrderId', 'apiKey', 'signature', 'timestamp'],
    'orderList.place': ['symbol', 'side', 'price', 'quantity', 'stopPrice', 'stopLimitPrice', 'stopLimitTimeInForce', 'newOrderRespType', 'apiKey', 'signature', 'timestamp'],
    'orderList.cancel': ['symbol', 'orderListId', 'apiKey', 'signature', 'timestamp'],
    'openOrderLists.status': ['apiKey', 'signature', 'timestamp'],
    'sor.order.place': ['symbol', 'side', 'type', 'quantity', 'timeInForce', 'price', 'timestamp', 'apiKey', 'signature',],
    'sor.order.test': ['symbol', 'side', 'type', 'quantity', 'timeInForce', 'price', 'timestamp', 'apiKey', 'signature',],
    'account.status': ['apiKey', 'signature', 'timestamp',],
    'account.rateLimits.orders': ['apiKey', 'signature', 'timestamp',],
    'account.commission': ['symbol', 'apiKey', 'signature', 'timestamp',],
    'allOrders': ['symbol', 'startTime', 'endTime', 'limit', 'apiKey', 'signature', 'timestamp',],
    'allOrderLists': ['startTime', 'endTime', 'limit', 'apiKey', 'signature', 'timestamp',],
    'myTrades': ['symbol', 'startTime', 'endTime', 'apiKey', 'signature', 'timestamp',],
    'myPreventedMatches': ['symbol', 'orderId', 'apiKey', 'signature', 'timestamp',],
    'myAllocations': ['symbol', 'orderId', 'apiKey', 'signature', 'timestamp',],
  },
})
