import { RequestModel } from '../models/request.model.js'

export const endpoints = {
  '': new RequestModel('GET', '/api/v3/ping', [], [], []),
  '': new RequestModel('GET', '/api/v3/time', [], [], []),
  '': new RequestModel('GET', '/api/v3/exchangeInfo', [], [], []),
  '': new RequestModel('GET', '/api/v3/depth', [], [], []),
  '': new RequestModel('GET', '/api/v3/trades', [], [], []),
  '': new RequestModel('GET', '/api/v3/myTrades', [], [], []),
  '': new RequestModel('GET', '/api/v3/aggTrades', [], [], []),
  '': new RequestModel('GET', '/api/v3/historicalTrades', [], [], []),
  '': new RequestModel('GET', '/api/v3/klines', [], [], []),
  '': new RequestModel('GET', '/api/v3/uiKlines', [], [], []),
  '': new RequestModel('GET', '/api/v3/avgPrice', [], [], []),
  '': new RequestModel('GET', '/api/v3/ticker', [], [], []),
  '': new RequestModel('GET', '/api/v3/ticker/24hr', [], [], []),
  '': new RequestModel('GET', '/api/v3/ticker/tradingDay', [], [], []),
  '': new RequestModel('GET', '/api/v3/ticker/price', [], [], []),
  '': new RequestModel('GET', '/api/v3/ticker/bookTicker', [], [], []),
  //
  '': new RequestModel('GET', '/api/v3/openOrderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/account/commission', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/orderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/myAllocations', [], [], []),
  '': new RequestModel('GET', '/api/v3/myPreventedMatches', [], [], []),
  '': new RequestModel('GET', '/api/v3/myPreventedMatches', [], [], []),
  '': new RequestModel('GET', '/api/v3/account', [], [], []),
  '': new RequestModel('GET', '/api/v3/rateLimit/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/myPreventedMatches', [], [], []),
  '': new RequestModel('GET', '/api/v3/myAllocations', [], [], []),
  '': new RequestModel('GET', '/api/v3/account', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/myPreventedMatches', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/account', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/acccount', [], [], []),
  '': new RequestModel('GET', '/api/v3/account', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/rateLimit/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/orderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/account', [], [], []),
  '': new RequestModel('GET', '/api/v3/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrders', [], [], []),
  '': new RequestModel('GET', '/api/v3/orderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/allOrderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/openOrderList', [], [], []),
  '': new RequestModel('GET', '/api/v3/account', [], [], []),
  '': new RequestModel('GET', '/api/v3/rateLimit/order', [], [], []),
  '': new RequestModel('GET', '/api/v3/myPreventedMatches', [], [], []),
  '': new RequestModel('GET', '/api/v3/myAllocations', [], [], []),
  '': new RequestModel('GET', '/api/v3/account/commission', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/test', [], [], []),
  '': new RequestModel('POST', '/api/v3/sor/order/test', [], [], []),
  '': new RequestModel('POST', '/api/v3/userDataStream', [], [], []),
  '': new RequestModel('POST', '/api/v3/sor/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/sor/order/test', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/oco', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/oco', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/oco', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/oco', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/oco', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/test', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('POST', '/api/v3/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/oco', [], [], []),
  '': new RequestModel('POST', '/api/v3/sor/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/sor/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/sor/order/test', [], [], []),
  '': new RequestModel('POST', '/api/v3/sor/order', [], [], []),
  '': new RequestModel('POST', '/api/v3/userDataStream', [], [], []),
  '': new RequestModel('POST', '/api/v3/order/cancelReplace', [], [], []),
  '': new RequestModel('PUT', '/api/v3/userDataStream', [], [], []),
  '': new RequestModel('PUT', '/api/v3/userDataStream', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/userDataStream', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/order', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/orderList', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/order', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/order', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/orderList', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/order', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/order', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/order', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/openOrders', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/orderList', [], [], []),
  '': new RequestModel('DELETE', '/api/v3/userDataStream', [], [], []),
}

export const getEndpointsList = () => Array.from([
  'Binance Rest API',
  ...Object.keys(endpoints),
])

export const getEndpointsRequest = (endpoint) => {
  if (!endpoints[endpoint]) {
    return new RequestModel()
  }

  return endpoints[endpoint]
}
