name: GitHub pages

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github.io
        uses: actions/checkout@v3

      - name: Docker build
        run: docker-compose build
