name: GitHub pages

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - using: 'docker'
        image: 'Dockerfile'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

